  services:
    redis:
      container_name: redis
      image: redis
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --save 60 1 --loglevel warning
    todobackend:
      build: .
      container_name: todobackend
      command: gunicorn app.wsgi --bind 0.0.0.0:8080
      volumes:
        - ./:/app
        - static_volume:/app/static
        - media_volume:/app/media
      expose:
        - "8080"
      environment:
        - SECRET_KEY=test
        - DEBUG=False
      depends_on:
        - redis
    nginx:
      image: nginx
      container_name: nginx
      restart: always
      ports: 
        - "80:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/home/app/static
        - media_volume:/home/app/media
      depends_on:
        - redis
        - todobackend   
  volumes:
    static_volume:
    media_volume:
