  services:
    backend:
      build: .
      container_name: mybackend
      command: python manage.py runserver 0.0.0.0:8080
      volumes:
        - ./:/app
      ports:
        - "8080:8080"
      environment:
        - SECRET_KEY=test
        - DEBUG=True