version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  todobackend:
    build: .
    container_name: todobackend
    command: gunicorn app.wsgi --bind 0.0.0.0:8080
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8080"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
      - DATABASE_URL=postgresql://todouser:todopass@postgres:5432/tododb
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app worker --loglevel=info
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - SECRET_KEY=test
      - DEBUG=False
      - DATABASE_URL=postgresql://todouser:todopass@postgres:5432/tododb
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
      - todobackend

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A app beat --loglevel=info
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - SECRET_KEY=test
      - DEBUG=False
      - DATABASE_URL=postgresql://todouser:todopass@postgres:5432/tododb
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
      - todobackend

  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - todobackend

volumes:
  postgres_data:
  static_volume:
  media_volume: