# Generated by Django 4.2 on 2025-04-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
