name: Docker Test & Deploy


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Launch Docker Compose 
      run: docker compose -f docker-compose-stage.yml up -d
    - name: Run pytest
      run: docker exec todobackend pytest 
    - name: Run flake8
      run: docker exec todobackend flake8

  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Connect & Exec. Commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: |
          cd ${{secrets.PROJECT_PATH}}
          docker-compose -f docker-compose-stage.yml stop
          git pull
          docker-compose -f docker-compose-stage.yml restart
